### ISSUE TITLE
Allow file specification in target command.

### ISSUE THREAD

**Issue by pkar** [upsight/ron#11]
More of a proposal and just a thought, but right now when targets are loaded from multiple files, they all get merged into the same namespace. Some hacks are to prepend or append a prefix, for example:

```
$ ron t apis_my-api_build
$ ron t apis_my-other-api_build
```

Would it would be better to be able to specify where the command came from in such a way:

```

$ ron t default.yaml:apis:my-api:build
# or
$ ron t default:apis:my-api:build
```

Where the first argument (default.yaml/default) is the filename from which to search for the command. In this case in default.yaml look for apis:my-api:build.

```
# default.yaml
apis:
    my-api:
         build:
             cmd: |
                  echo building
```

```
# ron.yaml
apis:
    my-other-api:
         build:
             cmd: |
                  echo building
```

```
$ ron t ron.yaml:apis:my-other-api:build
```

This would have to remove any bash completion options more than likely
